#:schema https://www.schemastore.org/typst.json
[package]
name = "indonesian"
entrypoint = "lib.typ"
authors = ["@stnDinus"]
license = "GPL-3.0-only"
description = "Translations for Bahasa Indonesia"
version = "0.0.1"
